### ISSUE TITLE
Issue with OAS 3.1 - unknown keyword: "unevaluatedProperties"?

### ISSUE THREAD

**Issue by p-bakker** [seriousme/openapi-schema-validator#180]
Hi,

Not sure if this is a problem with this library, another library or just user error, but I'm getting this error when using openapiGlue and I think I traced it to the AJV validator that I think is contributed by this library: `FastifyError [Error]: Failed building the validation schema for GET: /invoices, due to error strict mode: unknown keyword: "unevaluatedProperties"`

The relevant part of my OAS spec:
```
paths:
  /invoices:
    get:
     ....
      parameters:
        - $ref: '#/components/parameters/GenericFilter'
        - ....
```

```
components:
  parameters:
    GenericFilter:
      name: typedFilter
      in: query
      required: true
      schema:
        anyOf:
          - type: object
            unevaluatedProperties: {}
          - type: array
            items:
              type: object
              unevaluatedProperties: {}
      explode: false
```

AFAICT the above is valid OAS 3.1 spec...

Any thoughts?
