### ISSUE TITLE
Add local file reference to README

### ISSUE THREAD

**Issue by devs-ryan** [seriousme/openapi-schema-validator#50]
If i have a file file structure like:

api.v0.yaml
v0/auth.v0.yaml

I want to validate `api.v0.yaml` that references `v0/auth.v0.yaml`.

```
  /v0/auth/register:
    post:
      $ref: v0/auth.v0.yaml#/paths/~1v0~1auth~1register/post
      tags:
        - Auth
      summary: Register a new account
```

I get `must NOT have unevaluated properties`, which I understand is expected behaviour from the README, I can't figure out how to use `<instance>.addSpecRef(subSpecification, uri)` to get this working. 

Thanks
